config/routes.rb
Rails.application.routes.draw do

  # 管理者 admin
  devise_for :admin_users, controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :admin_users, only:[:index, :show, :edit, :update] do
      get :edit_pass, on: :member
    end
    resources :end_users, only:[:index, :show, :edit, :update]
    resources :areas, only:[:index, :create, :edit, :update]
    resources :jobs, only:[:index, :create, :edit, :update]
    resources :notifications, only: :index
    resources :trees, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      post :confirm, on: :collection
      resources :responses, only:[:create, :edit, :update, :destroy]
    end
    resource :searches, only:[] do
      collection do
        get 'search'
        get 'admin_user_search'
        get 'end_user_search'
      end
    end
  end


  # 拠点担当者　public
  devise_for :end_users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    resources :end_users, only:[:index,:update] do
      collection do
        get 'mypage'
        get 'mypage_edit'
        get 'edit_pass'
      end
    end
    resources :notifications, only: :index
    resources :trees, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      post :confirm, on: :collection
      resources :responses, only:[:create, :edit, :update, :destroy]
    end
    get "search" => "searches"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord

  # バリデーション
  validates :name, presence: true

  # アソシエーション
  has_many :your_jobs, dependent: :destroy
  # N：Nの関係を追記することにより、中間テーブルにadmin_userを保存した時に一緒にほぞんできるようにする
  has_many :admin_users, through: :your_jobs
  has_many :trees, dependent: :destroy
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController

  # 業務マスタ一覧（新規登録）
  def index
    @job = Job.new
    @jobs = Job.all.page(params[:page])
  end

  # 業務新規登録
  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to admin_jobs_path
    else
      @jobs = Job.all.page(params[:page])
      render :index
    end
  end

  # 業務編集画面
  def edit
    @job = Job.find(params[:id])
  end

  # 業務更新機能
  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  # ストロングパラメータ
  private

  def job_params
    params.require(:job).permit(:name, :color, :is_deleted)
  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/views/admin/jobs/edit.html.erb
<!--<h1>Admin::Jobs#edit</h1>-->
<div class = "container-fluid">

  <div class = "row">
    <h5 class="mb-5 ml-3">業務マスタ編集</h5>
  </div>


  <%= form_with model: @job, url: admin_job_path(@job.id), method: :patch do |f| %>
    <div class="form-group row">
      <%= f.label :id, "ID", class: "col-md-2 offset-1" %>
      <div class="col-md-2"><%= @job.id%></div>
    </div>
    <div class="form-group row">
      <%= f.label :name, "業務名", class: "col-md-2 offset-1" %>
      <%= f.text_field :name, class: "col-md-2" %>
    </div>
    <div class="form-group row">
      <%= f.label :color, "色", class: "col-md-2 offset-1" %>
      <%= f.color_field :color, class: "col-md-2" %>
    </div>
    <div class="form-group row">
      <%= f.label :is_deleted, "業務ステータス", class: "col-md-2 offset-1" %>
      <%= f.radio_button :is_deleted, false, checked: true %>&emsp;
      <%= f.label :is_deleted, "有効", value: false %>&emsp;&emsp;
      <%= f.radio_button :is_deleted, true %>&emsp;
      <%= f.label :is_deleted, "廃止", value: true %>
    </div>
    <div class="form-group row offset-3 mt-4">
      <%= f.submit "変更を保存", class: "btn btn-secondary" %>
    </div>
  <% end %>

</div>

app/views/admin/jobs/index.html.erb
<!--<h1>Admin::Jobs#index</h1>-->
<div class = "container-fluid">
  <div class = "row">
    <h5 class="mb-5 offset-1">業務マスタ</h5>
  </div>

  <div class = "row">
    <div class="col-md-8 offset-1">
      <%= form_with model: @job, url: admin_jobs_path, method: :post do |f| %>
        <%= f.label :name, "業務名" %>
        <%= f.text_field :name, placeholder: "業務の名前を入力してください", class: "col-md-4" %>
        <%= f.color_field :color %>
        <%= f.submit "登録", class: "btn btn-secondary btn-sm" %>
      <% end %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>業務名</th>
            <th>カラー</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @jobs.each do |job| %>
            <% if job.is_deleted == true %>
              <tr class="table-secondary">
            <% else %>
              <tr>
            <% end %>
              <td><%= job.id %></td>
              <td><%= job.name %></td>
              <td><span style = "background-color:<%= job.color %>">&emsp;&emsp;&emsp;</span></td>
              <td><%= job.is_deleted ? "廃止":"有効" %></td>
              <td><%= link_to "編集", edit_admin_job_path(job.id), class: "btn btn-secondary btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class = "d-flex justify-content-center"><%= paginate @jobs %></div>
    </div>
  </div>
</div>