config/routes.rb
Rails.application.routes.draw do

  # 管理者 admin
  devise_for :admin_users, controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :admin_users, only:[:index, :show, :edit, :update] do
      get :edit_pass, on: :member
    end
    resources :end_users, only:[:index, :show, :edit, :update]
    resources :areas, only:[:index, :create, :edit, :update]
    resources :jobs, only:[:index, :create, :edit, :update]
    resources :notifications, only: :index
    resources :trees, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      post :confirm, on: :collection
      resources :responses, only:[:create, :edit, :update, :destroy]
    end
    resource :searches, only:[] do
      collection do
        get 'search'
        get 'admin_user_search'
        get 'end_user_search'
      end
    end
  end


  # 拠点担当者　public
  devise_for :end_users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    resources :end_users, only:[:index,:update] do
      collection do
        get 'mypage'
        get 'mypage_edit'
        get 'edit_pass'
      end
    end
    resources :notifications, only: :index
    resources :trees, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      post :confirm, on: :collection
      resources :responses, only:[:create, :edit, :update, :destroy]
    end
    get "search" => "searches"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # バリデーション
  validates :employee_number, presence: true, numericality: true, uniqueness: true, length: {is: 6}
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :area_id, presence: true


  #アソシエーション
  has_many :trees, dependent: :destroy
  has_many :responses, dependent: :destroy
  belongs_to :area

  has_one_attached :profile_image

  # 通知機能
  # 自分からの通知
  has_many :active_notifications, class_name: "Notification", foreign_key: "end_visitor_id", dependent: :destroy
  # 相手からの通知
  has_many :passive_notifications, class_name: "Notification", foreign_key: "end_visited_id", dependent: :destroy

   # 画像がない場合のno-image設定、画像リサイズ
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  # 氏名を表示するメソッド
  def name_display
    family_name + "　" + first_name
  end

  # 氏名を表示するメソッド短い
  def name_display_short
    family_name + first_name
  end

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController

  # 拠点担当者一覧
  def index
    @end_users = EndUser.all.order(:area_id, area_id: "ASC").page(params[:page])
    @areas = Area.where(is_deleted: false, admin_area_flag: false)
    @jobs = Job.where(is_deleted: false)

    # 検索
    if params[:area]
      # your_areaの対象
      @end_users = EndUser.where(area_id: params[:area]).page(params[:page])
      @bord_name = Area.find(params[:area]).name + " "
    end
  end

  def show
  end

  # 拠点担当者編集
  def edit
    @user_areas = Area.where(admin_area_flag: false).where(is_deleted: false)
    @end_user = EndUser.find(params[:id])
  end

  # 更新機能
  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admin_end_users_path
    else
      @user_areas = Area.where(admin_area_flag: false).where(is_deleted: false)
      render :edit
    end
  end

   # ストロングパラメータ
  def end_user_params
    params.require(:end_user).permit(:employee_number, :family_name, :first_name, :email, :area_id, :is_deleted, :password)
  end


end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<!--<h1>Admin::EndUsers#edit</h1>-->
<div class = "container-fluid">

  <div class = "row">
    <h5 class="mb-5 ml-3">拠点担当者情報編集</h5>
  </div>

  <%= form_with model: @end_user, url: admin_end_user_path(@end_user.id), method: :patch do |f| %>
    <div class="form-group row">
      <%= f.label :employee_number, "社員番号", class: "col-md-2" %>
      <%= f.text_field :employee_number, autofocus: true, autocomplete: "on", class: "col-md-2" %>
    </div>
    <div class="form-group row">
      <%= f.label :family_name, "名字", class: "col-md-2" %>
      <%= f.text_field :family_name, autofocus: true, autocomplete: "on", class: "col-md-2" %>
      <%= f.label :first_name, "名前", class: "col-md-1" %>
      <%= f.text_field :first_name, autofocus: true, autocomplete: "on", class: "col-md-2" %>
    </div>
    <div class="form-group row">
      <%= f.label "メールアドレス", class: "col-md-2" %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-md-2" %>
    </div>
    <!--<div class="form-group row">-->
    <!--  <%#= f.label :password, "パスワード" %>-->
    <!--  <%#= f.password_field :password %>-->
    <!--</div>-->
    <div class="form-group row">
      <%= f.label :profile_image, "プロフィール画像", class: "col-md-2" %>
      <%= f.file_field :profile_image, accept: "image/*" %>
    </div>
    <div class="form-group row">
      <%= f.label "所属拠点", class: "col-md-2" %>
      <%= f.collection_select(:area_id, @user_areas, :id, :name) %>
    </div>
    <div class="form-group row">
      <%= f.label :is_deleted, "ステータス", class: "col-md-2" %>
      <%= f.radio_button :is_deleted, false %>
      <%= f.label :is_deleted, "有効", value: false %>&emsp;
      <%= f.radio_button :is_deleted, true %>
      <%= f.label :is_deleted, "無効", value: true %>
    </div>
    <div class="form-group row offset-2 mt-4">
      <%= f.submit "変更を保存", class: "btn btn-secondary" %>
    </div>
  <% end %>

</div>

app/views/admin/end_users/index.html.erb
<!--<h1>Admin::EndUsers#index</h1>-->
<div class = "container-fluid">
  <div class = "row">
    <div class="col-md-3 border-right pl-4">
      <!--部分テンプレート：ジャンル検索-->
      <%= render 'layouts/side_end', areas: @areas %>
    </div>
    <div class="col-md-8">
      <h5 class="mb-5"><%= @bord_name %>拠点担当者</h5>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>社員番号</th>
            <th>名前</th>
            <th>所属拠点</th>
            <th>ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @end_users.each do |end_user| %>
            <% if end_user.is_deleted == true %>
              <tr class="table-secondary">
            <% else %>
              <tr>
            <% end %>
              <td><%= end_user.id %></td>
              <td><%= end_user.employee_number %></td>
              <td><%= end_user.name_display %></td>
              <td><%= end_user.area.name %></td>
              <td><%= end_user.is_deleted ? "無効":"有効" %></td>
              <td><%= link_to "編集", edit_admin_end_user_path(end_user.id), class: "btn btn-secondary btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class = "d-flex justify-content-center"><%= paginate @end_users %></div>
    </div>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<h1>Admin::EndUsers#show</h1>
<p>Find me in app/views/admin/end_users/show.html.erb</p>