config/routes.rb
Rails.application.routes.draw do

  # 管理者 admin
  devise_for :admin_users, controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :admin_users, only:[:index, :show, :edit, :update] do
      get :edit_pass, on: :member
    end
    resources :end_users, only:[:index, :show, :edit, :update]
    resources :areas, only:[:index, :create, :edit, :update]
    resources :jobs, only:[:index, :create, :edit, :update]
    resources :notifications, only: :index
    resources :trees, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      post :confirm, on: :collection
      resources :responses, only:[:create, :edit, :update, :destroy]
    end
    resource :searches, only:[] do
      collection do
        get 'search'
        get 'admin_user_search'
        get 'end_user_search'
      end
    end
  end


  # 拠点担当者　public
  devise_for :end_users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    resources :end_users, only:[:index,:update] do
      collection do
        get 'mypage'
        get 'mypage_edit'
        get 'edit_pass'
      end
    end
    resources :notifications, only: :index
    resources :trees, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
      post :confirm, on: :collection
      resources :responses, only:[:create, :edit, :update, :destroy]
    end
    get "search" => "searches"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_message.erb
<!--メッセージ表示-->
<div>
  <% flash.each do |key, value| %>
      <p class="alert alert-info">
        <%= value %>
      </p>
  <% end %>
</div>

app/views/layouts/_search.html.erb
<!--部分テンプレート-->
<!--admin tree#index,show,_notification  public tree#index,show,_notification-->
<!--検索機能-->
</br>
<% if admin_user_signed_in? %>
  <%= form_with url: search_admin_searches_path, method: :get do |f| %>
    <%= f.text_field :keyword, placeholder: "質問・回答検索" %>
    <%= f.submit "検索", class: "btn btn-secondary btn-sm" %>
  <% end %><br></br>
<% else %>
  <%= form_with url: search_path, method: :get do |f| %>
    <%= f.text_field :keyword, placeholder: "質問・回答検索" %>
    <%= f.submit "検索", class: "btn btn-secondary btn-sm" %>
  <% end %><br></br>
<% end %>

app/views/layouts/_side_navi.html.erb
<!--部分テンプレート-->
<!--admin tree#index,show,_notification  public tree#index,show,_notification-->

<!--アドミンユーザーがサインインしている場合-->
<% if admin_user_signed_in? %>
  <!--新着通知-->
  <% if admin_unchecked_notifications.any? %>
    <%= link_to  admin_notifications_path, class: "text-secondary" do %>
      新着通知  <i class="fa-solid fa-bell"></i>
    <% end %></br>
  <% else %>
    <%= link_to "新着通知", admin_notifications_path, class: "text-secondary" %></br>
  <% end %>
  <!--自分宛の質問-->
  <%= link_to "担当拠点", admin_trees_path(genre: "担当"), class: "text-secondary" %></br>
  <!--全ての質問-->
  <%= link_to "全ての質問", admin_trees_path(genre: "全て"), class: "text-secondary" %></br>
  <!--自分が送信した質問-->
  <%= link_to "自分の質問", admin_trees_path(genre: "送信"), class: "text-secondary" %>


  <!--拠点検索-->
  <div class="dropdown mt-5">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      拠点検索
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <% areas.each do |area| %>
        <%= link_to area.name, admin_trees_path(area: area.id), class: "dropdown-item", type: "button" %>
      <% end %>
    </div>
  </div>

  <!--業務検索-->
  <div class="dropdown mt-4">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      業務検索
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <% jobs.each do |job| %>
        <%= link_to job.name, admin_trees_path(job: job.id), class: "dropdown-item", type: "button" %>
      <% end %>
    </div>
  </div>
<!--エンドユーザーがサインインしている場合-->
<% else %>
  <!--新着通知-->
  <% if end_unchecked_notifications.any? %>
    <%#= link_to "新着通知", notifications_path, class: "list-group-item list-group-item-action list-group-item-light" %>
    <!--<i class="fa-solid fa-bell"></i>-->
    <%= link_to notifications_path, class: "text-secondary" do %>
      新着通知  <i class="fa-solid fa-bell"></i>
    <% end %></br>
  <% else %>
    <%= link_to "新着通知", notifications_path, class: "text-secondary" %></br>
  <% end %>
  <!--自分宛の質問-->
  <%= link_to "担当拠点", trees_path(genre: "自拠点"), class: "text-secondary" %></br>

  <!--自分が送信した質問-->
  <%= link_to "自分の質問", trees_path(genre: "送信"), class: "text-secondary" %>


  <!--業務検索-->
  <div class="dropdown mt-4">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      業務検索
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <% jobs.each do |job| %>
        <%= link_to job.name, trees_path(job: job.id), class: "dropdown-item", type: "button" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_tree_index.html.erb
<!--部分テンプレート-->
<!--admin_user end_user  Tree#index-->
<!--本文-->

<div class = "row">
  <h5 class = "bg-light ml-3"><%= bord_name %></h5>
</div>
<div class = "row justify-content-center mb-5">
  <!--adminuserサインインの場合-->
  <% if admin_user_signed_in? %>
    <%= link_to "質問をする", new_admin_tree_path, class: "btn btn-secondary" %>
  <!--enduserサインインの場合-->
  <% else %>
    <%= link_to "質問をする", new_tree_path, class: "btn btn-secondary" %>
  <% end %>
</div>

<div class = "row">
  <div class = "col-md-12">

    <table class = "table table-hover ">
      <thead>
        <tr>
          <th>送信者</th>
          <th>宛先</th>
          <th>カテゴリ</th>
          <th>タイトル</th>
          <th>更新日</th>
          <th>回答数</th>
        </tr>
      </thead>

      <tbody>
        <% trees.each do |tree| %>
          <!--admin_userサインインの場合の動き-->
          <% if admin_user_signed_in? %>
          <!--新着の場合-->
            <% if h_appli_admin_unchecked_notifications_tree(tree.id).present? %>
              <tr class="tree_tbody_tr current_admin_qa" data-link="<%= admin_tree_path(tree.id) %>">
            <!--ツリーがクローズの場合-->
            <% elsif tree.is_closed == true %>
              <tr class="table-secondary tree_tbody_tr" data-link="<%= admin_tree_path(tree.id) %>">
            <!--それ以外-->
            <% else %>
              <tr class="tree_tbody_tr" data-link="<%= admin_tree_path(tree.id) %>">
            <% end %>
          <!--end_userサインインの場合の動き-->
          <% else %>
          <!--新着の場合-->
            <% if h_appli_end_unchecked_notifications_tree(tree.id).present? %>
              <tr class="tree_tbody_tr current_end_qa" data-link="<%= tree_path(tree.id) %>">
            <!--ツリーがクローズの場合-->
            <% elsif tree.is_closed == true %>
              <tr class="table-secondary tree_tbody_tr" data-link="<%= tree_path(tree.id) %>">
            <!--それ以外-->
            <% else %>
              <tr class="tree_tbody_tr" data-link="<%= tree_path(tree.id) %>">
            <% end %>
          <% end %>
              <td>
                <% if tree.end_user_id.nil? %><!--対象のツリーをadmin_userが投稿した場合-->
                  <%= tree.admin_user.area.name %>
                  <%= tree.admin_user.name_display_short %>
                <% else %><!--対象のツリーをend_userが投稿した場合-->
                  <strong><%= tree.end_user.area.name %></strong>
                  <%= tree.end_user.name_display_short %>
                <% end %>
              </td>
              <td>
                <% if tree.post_id == Area.find_by(admin_area_flag: true).id %>
                  <%= tree.post.name %>
                <% else %>
                  <strong><%= tree.post.name %></strong>
                <% end %>
                </td>
              <td><span style="background-color:<%= tree.job.color %>">&emsp;<%= tree.job.name %>&emsp;</span></td>
              <!--<td><%#= link_to tree.title.truncate(20), admin_tree_path(tree.id), class: "text-decoration-none text-dark" %></td>-->
              <td><%= tree.title.truncate(20) %></td>
              <td>
                <%= l tree.updated_at, format: :short %>
                <!--レスポンスの新規投稿、編集でツリーの更新日を変えていなかったので、レスポンスがあったら、最新のレスポンスの更新日、なかったらツリーの更新日を表示していたー-->
                <%# if tree.responses.exists? %>
                  <%#= l tree.latest_response.updated_at, format: :short %>
                <%# else %>
                  <%#= l tree.updated_at, format: :short %>
                <%# end %>
              </td>
              <td>
                <%= tree.responses.count %>
                <% if tree.is_closed == true %>
                   終了
                <% end %>
                <!--ログイン中のユーザーのレスポンス含め未読がある場合-->
                <% if (admin_user_signed_in? && h_appli_admin_unchecked_notifications_tree(tree.id).present?) || (end_user_signed_in? && h_appli_end_unchecked_notifications_tree(tree.id).present?) %>
                  <i class="fa-solid fa-bell"></i>
                <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>
<div class = "d-flex justify-content-center"><%= paginate trees %></div>

app/views/layouts/_tree_show.html.erb
<!--部分テンプレート-->
<!--admin_user end_user  Tree#show-->
<!--本文-->

<!--ツリー-->
<div class = "row mb-4">
  <div class = "col-md-9">
    <div class = "card border-secondary mb-5">
      <!--signed_inを追加これがないと、current_~user.idをした時に、サインインしていない方が、nomethoderrorになるため-->
      <!--ログインしているアドミンユーザーの投稿-->
      <% if admin_user_signed_in? && tree.admin_user_id == current_admin_user.id %>
        <div class = "card-header current_admin">
      <!--ログインしているエンドユーザーの投稿-->
      <% elsif end_user_signed_in? && tree.end_user_id == current_end_user.id %>
        <div class = "card-header current_end">
      <!--ログインユーザー以外のアドミンユーザーの投稿-->
      <% elsif tree.end_user_id.nil? %>
        <div class = "card-header other_admin">
      <!--ログインユーザー以外のエンドユーザー投稿-->
      <% else %>
        <div class = "card-header other_end">
      <% end %>
        <div class = "row">
          <div class = "col"><%= tree.title %></div>
        </div>
      </div>
      <div class = "card-header bg-white">
        <div class = "row">
          <div class = "col-sm-2">投稿日</div>
          <div class = "col-sm-8">更新日：<%= l tree.updated_at %></br> (投稿日：<%= l tree.created_at %>)</div>
        </div>
      </div>
      <div class = "card-header bg-white">
        <div class = "row">
          <div class = "col-sm-2">送信者</div>
          <div class = "col-sm-8">
            <% if tree.end_user_id.nil? %><!--対象のツリーをadmin_userが投稿した場合-->
              <%= tree.admin_user.area.name %>
              <%= tree.admin_user.name_display_short %>
            <% else %><!--対象のツリーをend_userが投稿した場合-->
              <strong><%= tree.end_user.area.name %></strong>
              <%= tree.end_user.name_display_short %>
            <% end %>
          </div>
        </div>
      </div>
      <div class = "card-header bg-white">
        <div class= "row">
          <div class = "col-sm-2">宛先</div>
          <div class = "col-sm-8"><%= tree.post.name %></div>
        </div>
      </div>
      <div class = "card-header bg-white">
        <div class= "row">
          <div class = "col-sm-2"></div>
          <div style="background-color:<%= tree.job.color %>"><strong>&emsp;<%= tree.job.name %>&emsp;</strong></div>
        </div>
      </div>
      <div class = "card-body">
        <div class = "row">
          <div class = "col-sm-2 d-flex align-items-center p-0">
            <% if tree.end_user_id.nil? %><!--対象のツリーをadmin_userが投稿した場合-->
              <%= image_tag tree.admin_user.get_profile_image(100,100),class: "img img-fluid rounded-circle" %>
            <% else %>  <!--対象のツリーをend_userが投稿した場合-->
              <%= image_tag tree.end_user.get_profile_image(100,100),class: "img img-fluid rounded-circle" %>
            <% end %>
          </div>
          <div class = "col-sm-8">
            <p class = "card-text"><%= simple_format(tree.body) %></p>
          </div>
        </div>
        <div class = "row border-top">
          <% if tree.attachments.attached? %>
            <div class = "col-sm-2">添付ファイル</div>
            <div class = "col-sm-8">
              <ul>
                <% tree.attachments.each do |obj| %>
                  <% url = rails_blob_path(obj) %>
                  <li><%= link_to CGI.unescape(File.basename(url)),url %></li>
                  <%#= link_to File.basename(rails_blob_path(obj)), rails_blob_path(obj) %>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
      <div class = "card-footer d-flex justify-content-end bg-white">
        <!--<div class = "btn btn-info btn-sm mr-auto">-->
          <%#= @tree.job.name %>
        <!--</div>-->

        <!--admin_userサインインの場合-->
        <% if admin_user_signed_in? %>
          <!--現在ログインしているユーザーの投稿-->
          <% if current_admin_user == tree.admin_user %>
            <%= link_to "修正する", edit_admin_tree_path(tree.id), class: "btn btn-secondary mr-2" %>
            <%= link_to "削除する", admin_tree_path(tree.id), method: :delete, "data-confirm" => "ツリーを削除してもよろしいですか？全ての回答も削除されます", class: "btn btn-secondary mr-2" %>
          <% end %>
          <!--スレッドがクローズされている-->
          <% if tree.is_closed == false %>
            <%= link_to "＋回答する", admin_tree_path(tree.id, anchor: "response"), class: "btn btn-secondary" %>
          <% end %>
        <!--end_user_サインインの場合-->
        <% else %>
          <!--現在ログインしているユーザーの投稿-->
          <% if current_end_user == tree.end_user %>
            <%= link_to "修正する", edit_tree_path(tree.id), class: "btn btn-secondary mr-2" %>
            <%= link_to "削除する", tree_path(tree.id), method: :delete, "data-confirm" => "ツリーを削除してもよろしいですか？全ての回答も削除されます", class: "btn btn-secondary mr-2" %>
          <% end %>
          <!--スレッドがクローズされている-->
          <% if @tree.is_closed == false %>
            <%= link_to "＋回答する", tree_path(tree.id, anchor: "response"), class: "btn btn-secondary" %>
          <% end %>
        <% end %>

        <!--<%# if (admin_user_signed_in? && (current_admin_user == @tree.admin_user)) || (end_user_signed_in? && (current_end_user == @tree.end_user)) %>-->
        <!--  <%#= link_to "修正する", edit_admin_tree_path(@tree.id), class: "btn btn-secondary mr-2" %>-->
        <!--  <%#= link_to "削除する", admin_tree_path(@tree.id), method: :delete, "data-confirm" => "ツリーを削除してもよろしいですか？全ての回答も削除されます", class: "btn btn-secondary mr-2" %>-->
        <!--<%# end %>-->
        <!--スレッドがクローズされていない場合、回答するを表示し、指定の場所に飛ぶようにする-->
        <!--<%# if @tree.is_closed == false %>-->
        <!--  <%#= link_to "＋回答する", admin_tree_path(@tree.id, anchor: "response"), class: "btn btn-secondary" %>-->
        <!--<%# end %>-->
      </div>
    </div>
  </div>
</div>

<!--レスポンス-->
<% responses.each do |res| %>
  <div class = "row">
    <div class = "col-md-9">
      <div class = "card border-secondary mb-3">
        <!--signed_inを追加これがないと、current_~user.idをした時に、サインインしていない方が、nomethoderrorになるため-->
        <!--ログインしているアドミンユーザーの投稿-->
        <% if admin_user_signed_in? && res.admin_user_id == current_admin_user.id %>
          <div class = "card-header current_admin">
        <!--ログインしているエンドユーザーの投稿-->
        <% elsif end_user_signed_in? && res.end_user_id == current_end_user.id %>
          <div class = "card-header current_end">
        <!--ログインユーザー以外のアドミンユーザーの投稿-->
        <% elsif res.end_user_id.nil? %>
          <div class = "card-header other_admin">
        <!--ログインユーザー以外のエンドユーザー投稿-->
        <% else %>
          <div class = "card-header other_end">
        <% end %>

          <div class = "text-left">
            <%= l res.updated_at %>
            <% if res.end_user_id.nil? %><!--対象のツリーをadmin_userが投稿した場合-->
              <%= res.admin_user.area.name %>
              <%= res.admin_user.name_display_short %>
            <% else %><!--対象のツリーをend_userが投稿した場合-->
              <%= res.end_user.area.name %>
              <%= res.end_user.name_display_short %>
            <% end %>
          </div>
        </div>
        <div class = "card-body">
          <div class = "row">
            <div class = "col-sm-2 d-flex align-items-center p-0">
              <% if res.end_user_id.nil? %><!--対象のツリーをadmin_userが投稿した場合-->
                <%= image_tag res.admin_user.get_profile_image(100,100),class: "img img-fluid rounded-circle" %>
              <% else %><!--対象のツリーをend_userが投稿した場合-->
                <%= image_tag res.end_user.get_profile_image(100,100),class: "img img-fluid rounded-circle" %>
              <% end %>
            </div>
            <div class = "col-sm-8">
              <p class = "card-text"><%= simple_format(res.body) %></p>
            </div>
          </div>
          <div class = "row border-top">
            <% if res.resattachments.attached? %>
              <div class = "col-sm-2">添付ファイル</div>
              <div class = "col-sm-8">
                <ul>
                  <% res.resattachments.each do |resobj| %>
                    <% url = rails_blob_path(resobj) %>
                    <li><%= link_to CGI.unescape(File.basename(url)),url %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </div>

          <!--admin_userサインインの場合-->
          <% if admin_user_signed_in? %>
            <!--現在ログインしているユーザーの投稿-->
            <% if current_admin_user == res.admin_user %>
              <div class = "row d-flex justify-content-end">
                <%= link_to "修正する", edit_admin_tree_response_path(tree.id, res.id), class: "btn btn-secondary mr-2" %>
                <%= link_to "削除する", admin_tree_response_path(tree.id, res.id), method: :delete, "data-confirm" => "回答を削除してもよろしいですか？", class: "btn btn-secondary mr-2" %>
              </div>
            <% end %>
          <!--end_user_サインインの場合-->
          <% else %>
            <!--現在ログインしているユーザーの投稿-->
            <% if current_end_user == res.end_user %>
              <div class = "row d-flex justify-content-end">
                <%= link_to "修正する", edit_tree_response_path(tree.id, res.id), class: "btn btn-secondary mr-2" %>
                <%= link_to "削除する", tree_response_path(tree.id, res.id), method: :delete, "data-confirm" => "回答を削除してもよろしいですか？", class: "btn btn-secondary mr-2" %>
              </div>
            <% end %>
          <% end %>

          <!--<%# if admin_user_signed_in? && current_admin_user == res.admin_user || end_user_signed_in? && current_end_user == res.end_user %>-->
          <!--  <div class = "row d-flex justify-content-end">-->
          <!--    <%#= link_to "修正する", edit_admin_tree_response_path(@tree.id, res.id), class: "btn btn-secondary mr-2" %>-->
          <!--    <%#= link_to "削除する", admin_tree_response_path(@tree.id, res.id), method: :delete, "data-confirm" => "回答を削除してもよろしいですか？", class: "btn btn-secondary mr-2" %>-->
          <!--  </div>-->
          <!--<%# end %>-->
        </div>
      </div>
    </div>
  </div>
<% end %>

<!--新規レス-->
<% if tree.is_closed == false %>
  <div class = "row">
    <div class = "col-md-9">
      <!--admin_userと、end_userでpost先が違うので、urlをインスタンス変数にし、コントローラで定義している-->
      <%= form_with model: newres, url: create_newres_url, method: :post do |f| %>
      <!--下の場合条件分岐したらエラーになったform_withをif_endで囲むため、endでformの終わりと認識されてしまう-->
      <!--<%# if admin_user_signed_in? %> -->
      <!--admin_userサインインの場合-->
      <!--  <%#= form_with model: @res, url: admin_tree_responses_path(@tree), method: :post do |f| %>-->
      <!--end_userサインインの場合-->
      <!--<%# else %>-->
      <!--  <#%= form_with model: @res, url: tree_responses_path(@tree), method: :post do |f| %>-->
      <!--<%# end %>-->
        <div class = "card mt-5">
          <!--ログインしているアドミンユーザ-->
          <% if admin_user_signed_in? %>
            <div class = "card-header current_admin_qa">
          <!--ログインしているエンドユーザ-->
          <% else %>
            <div class = "card-header current_end_qa">
          <% end %>
            <strong>回答する</strong>
        </div>

          <!--部分テンプレート：エラー-->
          <%= render 'layouts/error_message', model: f.object %>

          <div class = "card-body">
            <div class = "row">
              <%= f.text_area :body, autofocus: true,  placeholder: "回答を入力してください", rows:10, class: "col-sm-12 " %>
            </div>
          </div>
          <div class = "card-footer">
            <div class = "row">
              <%= f.label "添付ファイル(複数可)", class: "col-md-3" %>
              <%= f.file_field :resattachments, multiple: true %>
            </div>
          </div>
          <div class = "card-footer", id = "response">
            <div class = "row">
              <%= f.label :is_closed, "質問を終了する", class: "col-md-3" %>
              <div class = "col-sm-3 pl-0"><%= f.select :is_closed, options_for_select([["", false], ["質問をクローズする", true]]) %></div>
              <div class = "col-md-10 offset-1 "><small class="text-muted">
                質問をクローズする場合は「質問をクローズする」選んでください。</br>
                クローズすると、これ以降、このスレッドに返信はできなくなります
              </small></div>
            </div>
            <div class = "row d-flex justify-content-end">
              <%= f.submit "回答する", "data-confirm" => "質問をクローズするを選択した場合は、今後回答ができなくなります", class: "btn btn-secondary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<div class = "d-flex justify-content-center"><%= paginate responses %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QAboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--FontAwesomeの読み込み-->
    <script src="https://kit.fontawesome.com/dc75088d57.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class = "navbar navbar-expand-lg navbar-light bg-light mb-4 flex-column">
        <div class = 'container-fluid'>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <% if admin_user_signed_in? %>
            <div class = "collapse navbar-collapse justify-content-start" id = "navbarNavDropdown">
              <ul class = 'navbar-nav'>
                <% if admin_unchecked_notifications.any? %>
                  <li class = "nav-item m-3"><i class="fa-solid fa-bell header_bell"></i></li>
                <% end %>
                <li class = "nav-item m-3">
                  <%= link_to "掲示板", admin_trees_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "管理者一覧", admin_admin_users_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "拠点担当者一覧", admin_end_users_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "拠点マスタ", admin_areas_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "業務マスタ", admin_jobs_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "マイページ", admin_admin_user_path(current_admin_user.id), class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "ログアウト", destroy_admin_user_session_path, method: :delete, class: "nav-link active" %>
                </li>
              </ul>
            </div>
            <div class="d-flex flex-column">
              <div><%= current_admin_user.employee_number %></div>
              <div><%= current_admin_user.area.name %></div>
              <div><%= current_admin_user.name_display %></div>
            </div>

          <% elsif end_user_signed_in? %>
            <div class = "collapse navbar-collapse justify-content-start" id = "navbarNavDropdown">
              <ul class = 'navbar-nav'>
                <% if end_unchecked_notifications.any? %>
                  <li class = "nav-item m-3"><i class="fa-solid fa-bell header_bell"></i></li>
                <% end %>
                <li class = "nav-item m-3">
                  <%= link_to "掲示板", trees_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "拠点担当者一覧", end_users_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "マイページ", mypage_end_users_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: "nav-link active" %>
                </li>
              </ul>
            </div>
            <div class="d-flex flex-column">
              <div><%= current_end_user.employee_number %></div>
              <div><%= current_end_user.area.name %></div>
              <div><%= current_end_user.name_display %></div>
            </div>
          <% else %>
            <div class = "collapse navbar-collapse justify-content-start" id = "navbarNavDropdown">
              <ul class = 'navbar-nav'>
                <li class = "nav-item m-3">
                  <%= link_to "新規登録", new_end_user_registration_path, class: "nav-link active" %>
                </li>
                <li class = "nav-item m-3">
                  <%= link_to "ログイン", new_end_user_session_path, class: "nav-link active" %>
                </li>
              </ul>
          <% end %>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>